version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "save"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -P 3306 -p root | grep 'mysql is alive' || exit 1" ]
      interval: 2s
      retries: 15
    networks:
      - backend
    restart: on-failure
networks:
  backend:
    driver: bridge