version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "save"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      retries: 15
    networks:
      - backend
    restart: on-failure
  save:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "18000:18000"
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/actuator/healthy" ]
      interval: 5s
      retries: 10
    networks:
      - backend
    restart: on-failure
networks:
  backend:
    driver: bridge